import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  AlertTriangle, Archive, ArrowLeft, Check, ChevronDown, ChevronUp, Copy, Image,
  Link2, Lock, MessageSquare, Plus, RefreshCw, Save, ShieldCheck, Trash2, Users,
} from 'lucide-react';
import type { SeriesEpisode, SeriesProject, SeriesSeason } from '../../../types';
import type {
  CharacterActorAssignment, CharacterPossession, EditorialReview, EntityLinkType,
  ProductionRelationship, SeriesActor, SeriesAsset, SeriesChapter, SeriesCharacter,
  SeriesCoverProject, SeriesPermissionGrant, SeriesRole, SeriesStaffAssignment,
  SeriesStoryBlock, StoryBlockType, StoryScene,
} from '../../../types/seriesProduction';
import {
  archiveStoryScene, assertSeriesPermission, assignActorToCharacter, assignCharacterPossession,
  assignSeriesStaff, createDialogueBlock, createProductionChapter, createSeriesActor, createSeriesAsset,
  createSeriesCharacter, createStoryBlock, createStoryScene, deleteStoryBlock,
  duplicateStoryBlock, duplicateStoryScene, generateProductionContinuityWarnings,
  getActorAssignments, getCharacterPossessions, getCoverProjects, getEditorialReviews,
  getPermissionGrants, getProductionChapters, getProductionRelationships, getRevisionHistory,
  getScenesForChapter, getSeriesActors, getSeriesProductionAssets, getSeriesProductionCharacters,
  getSeriesStaff, getStoryBlockLinks, getStoryBlocks, hasSeriesPermission, linkStoryBlockEntity, publicStoryBlocks,
  moveStoryBlock, reorderStoryBlocks, reorderStoryScenes, saveCoverProject, saveEditorialReview,
  saveProductionRelationship, transferCharacterPossession, updateStoryBlock, updateStoryScene,
  updateSeriesAsset,
} from '../../../lib/seriesProductionRepository';

type Tab = 'story'|'scenes'|'chapters'|'cast'|'assets'|'locations'|'relationships'|'continuity'|'covers'|'editorial';
const tabs: Array<[Tab,string]> = [
  ['story','Story Builder'],['scenes','Scenes'],['chapters','Chapters'],
  ['cast','Cast & Characters'],['assets','Assets & Possessions'],['locations','Locations'],
  ['relationships','Relationships'],['continuity','Timeline & Continuity'],
  ['covers','Covers & Artwork'],['editorial','Editorial Review'],
];
const blockTypes:StoryBlockType[]=['heading','paragraph','dialogue','narration','quote','image','caption','list','table','scene-break','character-entry','location-entry','object-entry','internal-note'];
const roles:SeriesRole[]=['owner','lead-writer','co-writer','editor','story-architect','character-director','asset-manager','cover-designer','continuity-editor','publisher','viewer'];
const field='w-full border border-[#cfd3d7] bg-white px-2 py-2 text-xs outline-none focus:border-[#ff6321]';
const newId=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();

interface Props {
  project: SeriesProject;
  seasons: SeriesSeason[];
  episodes: SeriesEpisode[];
  currentUserId: string;
  currentUserName: string;
}

interface BlockEditorProps {
  block:SeriesStoryBlock; links:Array<{id:string;entityType:EntityLinkType;entityId:string;label:string}>;
  canEdit:boolean; onSave:(block:SeriesStoryBlock)=>Promise<void>; onDuplicate:()=>void; onDelete:()=>void;
  onMove:(direction:-1|1)=>void; onLink:()=>void; onInspect:(type:EntityLinkType,id:string)=>void;
  onMoveTo:()=>void;
}
const StoryBlockEditor:React.FC<BlockEditorProps>=({block,links,canEdit,onSave,onDuplicate,onDelete,onMove,onLink,onInspect,onMoveTo})=>{
  const [draft,setDraft]=useState(block);const [state,setState]=useState<'saved'|'dirty'|'saving'|'error'>('saved');
  const [error,setError]=useState('');const [lastSaved,setLastSaved]=useState(block.updatedAt);const timer=useRef<ReturnType<typeof setTimeout>>();
  useEffect(()=>{setDraft(block);setState('saved');},[block]);
  const save=async(value=draft)=>{if(timer.current)clearTimeout(timer.current);setState('saving');try{await onSave(value);setLastSaved(now());setState('saved');setError('');}catch(cause){setState('error');setError(cause instanceof Error?cause.message:'Save failed.');}};
  const change=(value:string)=>{const next={...draft,content:value,updatedAt:now()};setDraft(next);setState('dirty');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(next),650);};
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
  return <article draggable={canEdit} data-block-id={block.id} className={`border p-3 ${block.type==='internal-note'?'border-amber-300 bg-amber-50':'border-[#d8dcdf] bg-white'}`}>
    <div className="flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] font-extrabold uppercase text-[#ff6321]">{block.type}</span><span className={`text-[10px] font-bold ${state==='error'?'text-red-700':'text-[#667]'}`}>{state==='saved'?`Saved ${new Date(lastSaved).toLocaleTimeString()}`:state==='dirty'?'Unsaved':state==='saving'?'Saving…':'Save failed'}</span></div>
    {block.type==='image'?<div className="mt-2 border border-dashed p-6 text-center text-xs text-[#777]"><Image className="mx-auto h-5 w-5" />{draft.imageAssetId||'Choose linked image asset'}</div>:<textarea aria-label={`${block.type} content`} disabled={!canEdit} rows={block.type==='heading'?1:3} value={draft.content} onChange={(e)=>change(e.target.value)} className={`${field} mt-2 disabled:bg-[#f1f2f3]`} />}
    <div className="mt-2 flex flex-wrap gap-1">{links.map((link)=><button key={link.id} onClick={()=>onInspect(link.entityType,link.entityId)} className="inline-flex items-center gap-1 rounded-full border border-[#ffb18f] bg-[#fff5f0] px-2 py-1 text-[10px] font-bold"><Link2 className="h-3 w-3"/>{link.label}</button>)}</div>
    {error&&<div role="alert" className="mt-2 flex items-center justify-between bg-red-50 p-2 text-xs text-red-800"><span>{error}</span><button onClick={()=>void save()} className="font-bold">Retry</button></div>}
    {canEdit&&<div className="mt-2 flex gap-1"><button title="Move up" onClick={()=>onMove(-1)}><ChevronUp className="h-4 w-4"/></button><button title="Move down" onClick={()=>onMove(1)}><ChevronDown className="h-4 w-4"/></button><button title="Move to scene" onClick={onMoveTo} className="px-1 text-[10px] font-bold">Move</button><button title="Duplicate" onClick={onDuplicate}><Copy className="h-4 w-4"/></button><button title="Link entity" onClick={onLink}><Link2 className="h-4 w-4"/></button><button title="Delete" onClick={onDelete} className="ml-auto text-red-700"><Trash2 className="h-4 w-4"/></button><button onClick={()=>void save()}><Save className="h-4 w-4"/></button></div>}
  </article>;
};

export const InteractiveSeriesProductionStudio:React.FC<Props>=({project,seasons,episodes,currentUserId,currentUserName})=>{
  const [tab,setTab]=useState<Tab>('story');const [episodeId,setEpisodeId]=useState(episodes[0]?.id||'');
  const [chapters,setChapters]=useState<SeriesChapter[]>([]);const [chapterId,setChapterId]=useState('');
  const [scenes,setScenes]=useState<StoryScene[]>([]);const [sceneId,setSceneId]=useState('');
  const [blocks,setBlocks]=useState<SeriesStoryBlock[]>([]);const [links,setLinks]=useState<Record<string,BlockEditorProps['links']>>({});
  const [staff,setStaff]=useState<SeriesStaffAssignment[]>([]);const [grants,setGrants]=useState<SeriesPermissionGrant[]>([]);
  const [characters,setCharacters]=useState<SeriesCharacter[]>([]);const [actors,setActors]=useState<SeriesActor[]>([]);
  const [cast,setCast]=useState<CharacterActorAssignment[]>([]);const [assets,setAssets]=useState<SeriesAsset[]>([]);
  const [possessions,setPossessions]=useState<CharacterPossession[]>([]);const [relationships,setRelationships]=useState<ProductionRelationship[]>([]);
  const [covers,setCovers]=useState<SeriesCoverProject[]>([]);const [reviews,setReviews]=useState<EditorialReview[]>([]);
  const [error,setError]=useState('');const [inspector,setInspector]=useState<{type:string;id:string}>();const [mobileTree,setMobileTree]=useState(true);
  const selectedEpisode=episodes.find((item)=>item.id===episodeId);const selectedChapter=chapters.find((item)=>item.id===chapterId);const selectedScene=scenes.find((item)=>item.id===sceneId);
  const target={scopeType:'scene' as const,scopeId:sceneId||project.id,ancestors:[{scopeType:'series' as const,scopeId:project.id},{scopeType:'episode' as const,scopeId:episodeId},{scopeType:'chapter' as const,scopeId:chapterId}]};
  const can=(permission:Parameters<typeof hasSeriesPermission>[1])=>hasSeriesPermission(currentUserId,permission,target,staff,grants);
  const guard=(permission:Parameters<typeof assertSeriesPermission>[1])=>assertSeriesPermission(currentUserId,permission,target,staff,grants);

  const loadGlobal=useCallback(async()=>{const [nextStaff,nextGrants,nextCharacters,nextActors,nextCast,nextAssets,nextPossessions,nextRelationships,nextCovers,nextReviews]=await Promise.all([getSeriesStaff(project.id),getPermissionGrants(project.id),getSeriesProductionCharacters(project.id),getSeriesActors(project.id),getActorAssignments(project.id),getSeriesProductionAssets(project.id),getCharacterPossessions(project.id),getProductionRelationships(project.id),getCoverProjects(project.id),getEditorialReviews(project.id)]);
    if(nextStaff.length===0){const owner=await assignSeriesStaff({seriesId:project.id,userId:currentUserId,displayName:currentUserName,role:'owner',scopeType:'series',scopeId:project.id,active:true});nextStaff.push(owner);}
    setStaff(nextStaff);setGrants(nextGrants);setCharacters(nextCharacters);setActors(nextActors);setCast(nextCast);setAssets(nextAssets);setPossessions(nextPossessions);setRelationships(nextRelationships);setCovers(nextCovers);setReviews(nextReviews);
  },[currentUserId,currentUserName,project.id]);
  const loadChapters=useCallback(async(id:string)=>{const next=await getProductionChapters(id);setChapters(next);setChapterId((current)=>next.some((item)=>item.id===current)?current:next[0]?.id||'');},[]);
  const loadScenes=useCallback(async(id:string)=>{const next=await getScenesForChapter(id);setScenes(next);setSceneId((current)=>next.some((item)=>item.id===current)?current:next[0]?.id||'');},[]);
  const loadBlocks=useCallback(async(id:string)=>{const next=await getStoryBlocks(id);setBlocks(next);const entries=await Promise.all(next.map(async(block)=>[block.id,await getStoryBlockLinks(block.id)] as const));const result:Record<string,BlockEditorProps['links']>={};for(const [blockId,blockLinks] of entries)result[blockId]=blockLinks;setLinks(result);},[]);
  useEffect(()=>{void loadGlobal().catch((cause)=>setError(String(cause)));},[loadGlobal]);
  useEffect(()=>{if(episodeId)void loadChapters(episodeId);},[episodeId,loadChapters]);
  useEffect(()=>{if(chapterId)void loadScenes(chapterId);else setScenes([]);},[chapterId,loadScenes]);
  useEffect(()=>{if(sceneId)void loadBlocks(sceneId);else setBlocks([]);},[loadBlocks,sceneId]);
  const run=async(operation:()=>Promise<void>,reload:()=>Promise<void>=loadGlobal)=>{setError('');try{await operation();await reload();}catch(cause){setError(cause instanceof Error?cause.message:'Production operation failed.');}};
  const addChapter=()=>selectedEpisode&&void run(async()=>{guard('create');const value=await createProductionChapter({seriesId:project.id,seasonId:selectedEpisode.seasonId,episodeId:selectedEpisode.id,chapterNumber:chapters.length+1,title:`Chapter ${chapters.length+1}`,synopsis:'',status:'draft',orderIndex:chapters.length});setChapterId(value.id);},()=>loadChapters(selectedEpisode.id));
  const addScene=()=>selectedEpisode&&selectedChapter&&void run(async()=>{guard('create');const value=await createStoryScene({seriesId:project.id,seasonId:selectedEpisode.seasonId,episodeId:selectedEpisode.id,chapterId:selectedChapter.id,sceneNumber:scenes.length+1,title:`Scene ${scenes.length+1}`,purpose:'',synopsis:'',openingSituation:'',conflict:'',turningPoint:'',outcome:'',characterIds:[],assetIds:[],possessionIds:[],storyTime:'',weather:'',status:'draft',orderIndex:scenes.length});setSceneId(value.id);},()=>loadScenes(selectedChapter.id));
  const addBlock=(type:StoryBlockType)=>selectedScene&&selectedChapter&&void run(async()=>{guard('create');const block=await createStoryBlock({seriesId:project.id,chapterId:selectedChapter.id,sceneId:selectedScene.id,type,content:'',caption:'',orderIndex:blocks.length,createdBy:currentUserId});if(type==='dialogue'&&characters[0])await createDialogueBlock({seriesId:project.id,sceneId:selectedScene.id,storyBlockId:block.id,characterId:characters[0].id,actorId:cast.find((item)=>item.characterId===characters[0].id)?.actorId,dialogue:'',emotion:'',delivery:'',actionBefore:'',actionAfter:'',orderIndex:blocks.length});},()=>loadBlocks(selectedScene.id));
  const moveBlock=(blockId:string,direction:-1|1)=>{const index=blocks.findIndex((item)=>item.id===blockId),targetIndex=index+direction;if(index<0||targetIndex<0||targetIndex>=blocks.length)return;const next=[...blocks];[next[index],next[targetIndex]]=[next[targetIndex],next[index]];void run(async()=>{guard('edit');await reorderStoryBlocks(sceneId,next.map((item)=>item.id));},()=>loadBlocks(sceneId));};
  const warnings=useMemo(()=>generateProductionContinuityWarnings({scenes,characters,actors,cast,assets,possessions,relationships,covers}),[actors,assets,cast,characters,covers,possessions,relationships,scenes]);

  const tree=<aside className={`${mobileTree?'block':'hidden'} min-w-0 border border-[#cfd3d7] bg-[#24282c] text-white lg:block`}>
    <div className="border-b border-[#474c51] p-3"><strong className="text-sm">Series Tree</strong><select aria-label="Production episode" value={episodeId} onChange={(e)=>setEpisodeId(e.target.value)} className="mt-2 w-full border border-[#555] bg-[#30353a] p-2 text-xs">{seasons.flatMap((season)=>episodes.filter((episode)=>episode.seasonId===season.id).map((episode)=><option key={episode.id} value={episode.id}>S{season.seasonNumber} E{episode.episodeNumber} · {episode.title}</option>))}</select></div>
    <div className="p-2"><div className="flex items-center justify-between px-2 py-1 text-[10px] font-bold uppercase text-[#adb2b6]"><span>Chapters</span>{can('create')&&<button onClick={addChapter}><Plus className="h-4 w-4"/></button>}</div>{chapters.map((chapter)=><div key={chapter.id}><button onClick={()=>{setChapterId(chapter.id);setMobileTree(false);}} className={`w-full px-2 py-2 text-left text-xs font-bold ${chapterId===chapter.id?'bg-[#ff6321]':'hover:bg-[#34393e]'}`}>{chapter.chapterNumber}. {chapter.title}</button>{chapterId===chapter.id&&<div className="ml-3 border-l border-[#555] pl-2">{scenes.map((scene)=><button key={scene.id} onClick={()=>{setSceneId(scene.id);setMobileTree(false);}} className={`block w-full px-2 py-1.5 text-left text-[11px] ${sceneId===scene.id?'text-[#ff9d72]':'text-[#ddd]'}`}>Scene {scene.sceneNumber}: {scene.title}</button>)}{can('create')&&<button onClick={addScene} className="px-2 py-1 text-[10px] font-bold text-[#ff9d72]">+ Add scene</button>}</div>}</div>)}</div>
  </aside>;

  const story=<div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2 border border-[#d8dcdf] bg-white p-3"><div><p className="text-[10px] font-bold uppercase text-[#ff6321]">Rich story canvas</p><h3 className="font-extrabold">{selectedScene?.title||'Select or create a scene'}</h3></div>{can('create')&&<select aria-label="Insert story block" defaultValue="" onChange={(e)=>{if(e.target.value)addBlock(e.target.value as StoryBlockType);e.target.value='';}} className={field}><option value="">+ Insert block</option>{blockTypes.map((type)=><option key={type}>{type}</option>)}</select>}</div>
    <div className="space-y-2" onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{const id=e.dataTransfer.getData('text/plain');if(id)moveBlock(id,1);}}>{blocks.map((block)=><div key={block.id} onDragStart={(e)=>e.dataTransfer.setData('text/plain',block.id)}><StoryBlockEditor block={block} links={links[block.id]||[]} canEdit={can('edit')&&selectedScene?.status!=='locked'} onSave={async(next)=>{guard('edit');await updateStoryBlock(next,currentUserId);setBlocks((current)=>current.map((item)=>item.id===next.id?next:item));}} onDuplicate={()=>void run(async()=>{guard('create');await duplicateStoryBlock(block.id);},()=>loadBlocks(sceneId))} onDelete={()=>window.confirm('Delete this story block?')&&void run(async()=>{guard('delete');await deleteStoryBlock(block.id);},()=>loadBlocks(sceneId))} onMove={(direction)=>moveBlock(block.id,direction)} onMoveTo={()=>{const destination=window.prompt(`Destination scene ID:\n${scenes.map((item)=>`${item.id} (${item.title})`).join('\n')}`);const targetScene=scenes.find((item)=>item.id===destination);if(destination&&targetScene)void run(async()=>{guard('edit');await moveStoryBlock(block.id,targetScene.chapterId,targetScene.id,999);},()=>loadBlocks(sceneId));}} onLink={()=>{const type=window.prompt('Entity type: character, actor, asset, possession, location, relationship') as EntityLinkType|null;const entityId=window.prompt('Entity ID');if(type&&entityId)void run(async()=>{guard('edit');await linkStoryBlockEntity({blockId:block.id,entityType:type,entityId,label:`${type}: ${entityId}`,startOffset:0,endOffset:0});},()=>loadBlocks(sceneId));}} onInspect={(type,id)=>setInspector({type,id})}/></div>)}</div>
    {blocks.length===0&&<div className="border border-dashed bg-white p-10 text-center text-sm text-[#777]">Add a heading, paragraph, dialogue, image, scene break, entity entry, or private internal note.</div>}
  </div>;

  const inspectorPanel=<aside className="min-w-0 border border-[#d8dcdf] bg-white p-4"><p className="text-[10px] font-bold uppercase text-[#ff6321]">Scene inspector</p>{selectedScene?<div className="mt-2 space-y-3"><label className="block text-xs font-bold">Title<input disabled={!can('edit')} value={selectedScene.title} onChange={(e)=>setScenes((current)=>current.map((item)=>item.id===selectedScene.id?{...item,title:e.target.value}:item))} onBlur={()=>void run(async()=>{guard('edit');await updateStoryScene(selectedScene,currentUserId);},()=>loadScenes(chapterId))} className={field}/></label>{(['purpose','synopsis','openingSituation','conflict','turningPoint','outcome'] as const).map((key)=><label key={key} className="block text-xs font-bold capitalize">{key.replace(/([A-Z])/g,' $1')}<textarea disabled={!can('edit')} value={selectedScene[key]} onChange={(e)=>setScenes((current)=>current.map((item)=>item.id===selectedScene.id?{...item,[key]:e.target.value}:item))} className={field}/></label>)}<div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Story date<input type="date" value={selectedScene.storyDate||''} onChange={(e)=>setScenes((current)=>current.map((item)=>item.id===selectedScene.id?{...item,storyDate:e.target.value}:item))} className={field}/></label><label className="text-xs font-bold">Weather<input value={selectedScene.weather} onChange={(e)=>setScenes((current)=>current.map((item)=>item.id===selectedScene.id?{...item,weather:e.target.value}:item))} className={field}/></label></div><div className="flex flex-wrap gap-2">{can('create')&&<button onClick={()=>void run(async()=>{guard('create');await duplicateStoryScene(selectedScene.id);},()=>loadScenes(chapterId))} className="border px-2 py-1 text-xs"><Copy className="mr-1 inline h-3 w-3"/>Duplicate</button>}{can('lock')&&<button onClick={()=>void run(async()=>{guard('lock');await archiveStoryScene(selectedScene.id);},()=>loadScenes(chapterId))} className="border px-2 py-1 text-xs"><Archive className="mr-1 inline h-3 w-3"/>Archive</button>}</div></div>:<p className="mt-3 text-xs text-[#777]">Select a scene.</p>}
    {inspector&&<div className="mt-4 border-t pt-3"><strong className="text-xs">Linked {inspector.type}</strong><p className="break-all text-[11px]">{inspector.id}</p><button onClick={()=>setInspector(undefined)} className="mt-2 text-xs font-bold">Close</button></div>}</aside>;

  const castPanel=<section className="grid gap-4 lg:grid-cols-2"><div className="border bg-white p-4"><h3 className="font-extrabold">Fictional characters</h3><button onClick={()=>void run(async()=>{guard('create');await createSeriesCharacter({seriesId:project.id,name:`Character ${characters.length+1}`,aliases:[],description:'',status:'alive'});})} className="mt-2 border px-3 py-1 text-xs font-bold">+ Character</button><div className="mt-3 space-y-2">{characters.map((character)=><div key={character.id} className="border p-2 text-xs"><strong>{character.name}</strong><p>{character.status}</p></div>)}</div></div><div className="border bg-white p-4"><h3 className="font-extrabold">Actors & casting</h3><button onClick={()=>void run(async()=>{guard('create');await createSeriesActor({seriesId:project.id,name:`Actor ${actors.length+1}`,bio:'',contactNotes:''});})} className="mt-2 border px-3 py-1 text-xs font-bold">+ Actor</button><div className="mt-3 space-y-2">{actors.map((actor)=><div key={actor.id} className="border p-2 text-xs"><strong>{actor.name}</strong>{characters[0]&&<button onClick={()=>void run(async()=>{guard('edit');await assignActorToCharacter({seriesId:project.id,characterId:characters[0].id,actorId:actor.id,assignmentType:'primary',notes:''});})} className="ml-2 border px-2 py-0.5">Assign to {characters[0].name}</button>}</div>)}</div></div></section>;
  const assetsPanel=<section className="grid gap-4 lg:grid-cols-2"><div className="border bg-white p-4"><h3 className="font-extrabold">Assets</h3><button onClick={()=>void run(async()=>{guard('create');await createSeriesAsset({seriesId:project.id,name:`Asset ${assets.length+1}`,type:'other',description:'',status:'available',continuityNotes:''});})} className="mt-2 border px-3 py-1 text-xs font-bold">+ Asset</button>{assets.map((asset)=><div key={asset.id} className="mt-2 border p-2 text-xs"><strong>{asset.name}</strong> · {asset.type} · {asset.status}{characters[0]&&<button onClick={()=>void run(async()=>{guard('edit');await assignCharacterPossession({seriesId:project.id,assetId:asset.id,characterId:characters[0].id,status:'owned',notes:''});})} className="ml-2 border px-2">Assign</button>}{asset.status==='available'&&<><button onClick={()=>void run(async()=>{guard('edit');await updateSeriesAsset({...asset,status:'lost',lostSceneId:sceneId});})} className="ml-1 border px-2">Lost</button><button onClick={()=>window.confirm('Mark this asset destroyed?')&&void run(async()=>{guard('edit');await updateSeriesAsset({...asset,status:'destroyed',destroyedSceneId:sceneId});})} className="ml-1 border px-2">Destroyed</button></>}</div>)}</div><div className="border bg-white p-4"><h3 className="font-extrabold">Possessions</h3>{possessions.map((possession)=><div key={possession.id} className="mt-2 border p-2 text-xs"><strong>{assets.find((item)=>item.id===possession.assetId)?.name}</strong> · {possession.status}{characters[1]&&possession.status!=='transferred'&&<button onClick={()=>window.confirm('Confirm possession transfer?')&&void run(async()=>{guard('edit');await transferCharacterPossession(possession.id,characters[1].id,sceneId);})} className="ml-2 border px-2">Transfer</button>}</div>)}</div></section>;
  const relationshipsPanel=<section className="border bg-white p-4"><h3 className="font-extrabold">Relationship timeline</h3>{characters.length>=2&&<button onClick={()=>void run(async()=>{guard('create');await saveProductionRelationship({id:newId('relationship'),seriesId:project.id,sourceCharacterId:characters[0].id,targetCharacterId:characters[1].id,type:'unknown',trustLevel:50,conflictLevel:0,active:true,betrayal:'',reconciliation:'',description:'',createdAt:now(),updatedAt:now()});})} className="mt-2 border px-3 py-1 text-xs font-bold">+ Relationship</button>}{relationships.map((relationship)=><div key={relationship.id} className="mt-2 border p-3 text-xs"><strong>{characters.find((item)=>item.id===relationship.sourceCharacterId)?.name} ↔ {characters.find((item)=>item.id===relationship.targetCharacterId)?.name}</strong><p>{relationship.type} · Trust {relationship.trustLevel} · Conflict {relationship.conflictLevel}</p></div>)}</section>;
  const coversPanel=<section className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="border bg-white p-4"><h3 className="font-extrabold">Cover projects</h3><button onClick={()=>void run(async()=>{guard('create');await saveCoverProject({id:newId('cover'),seriesId:project.id,type:'series-cover',title:project.title,subtitle:project.subtitle,author:'',gradientStart:'#24282c',gradientEnd:'#ff6321',seriesBadge:'SERIES',seasonBadge:'',episodeBadge:'',actorIds:[],characterIds:[],price:'',status:'draft',createdAt:now(),updatedAt:now()});})} className="mt-2 border px-3 py-1 text-xs font-bold">+ Cover</button>{covers.map((cover)=><div key={cover.id} className="mt-2 border p-2 text-xs"><strong>{cover.type}</strong> · {cover.title} · {cover.status}</div>)}</div><div className="min-h-80 p-6 text-white" style={{background:`linear-gradient(135deg,${covers[0]?.gradientStart||'#24282c'},${covers[0]?.gradientEnd||'#ff6321'})`}}><span className="border px-2 py-1 text-[10px] font-bold">{covers[0]?.seriesBadge||'SERIES'}</span><h3 className="mt-16 text-3xl font-extrabold">{covers[0]?.title||project.title}</h3><p>{covers[0]?.subtitle}</p></div></section>;
  const editorialPanel=<div className="grid gap-4 xl:grid-cols-2"><section className="border bg-white p-4"><h3 className="font-extrabold">Editorial workflow</h3>{selectedScene&&<div className="mt-3 flex flex-wrap gap-2">{(['submitted','changes-requested','approved','locked'] as const).map((status)=><button key={status} onClick={()=>void run(async()=>{guard(status==='approved'?'approve':status==='locked'?'lock':'edit');await saveEditorialReview({id:newId('review'),seriesId:project.id,scopeType:'scene',scopeId:selectedScene.id,status,assignedTo:currentUserId,requestedBy:currentUserId,reviewedBy:status==='approved'?currentUserId:undefined,reviewNote:'',createdAt:now(),updatedAt:now()});},loadGlobal)} className="border px-2 py-1 text-xs">{status}</button>)}</div>}{reviews.map((review)=><div key={review.id} className="mt-2 border p-2 text-xs"><strong>{review.scopeType}</strong> · {review.status} · {review.reviewNote}</div>)}</section><section className="border bg-white p-4"><h3 className="font-extrabold">Staff access</h3>{can('manage-staff')&&<button onClick={()=>{const userId=window.prompt('Staff user ID');const role=window.prompt(`Role: ${roles.join(', ')}`) as SeriesRole|null;if(userId&&role&&roles.includes(role))void run(async()=>{guard('manage-staff');await assignSeriesStaff({seriesId:project.id,userId,displayName:userId,role,scopeType:'series',scopeId:project.id,active:true});});}} className="mt-2 border px-3 py-1 text-xs font-bold"><Users className="mr-1 inline h-3 w-3"/>Assign staff</button>}{staff.map((person)=><div key={person.id} className="mt-2 border p-2 text-xs"><strong>{person.displayName}</strong> · {person.role} · {person.scopeType}</div>)}</section></div>;

  let content:React.ReactNode=story;
  if(tab==='cast')content=castPanel;else if(tab==='assets')content=assetsPanel;else if(tab==='relationships')content=relationshipsPanel;else if(tab==='continuity')content=<section className="border bg-white p-4"><h3 className="font-extrabold">Continuity warnings</h3>{warnings.length?warnings.map((warning)=><div key={`${warning.code}-${warning.sceneId}-${warning.entityId}`} className="mt-2 flex gap-2 border border-amber-300 bg-amber-50 p-3 text-xs"><AlertTriangle className="h-4 w-4"/><span><strong>{warning.code}</strong>: {warning.message}</span></div>):<p className="mt-3 text-sm text-[#667]">No production continuity warnings.</p>}</section>;else if(tab==='covers')content=coversPanel;else if(tab==='editorial')content=editorialPanel;else if(tab==='chapters')content=<section className="border bg-white p-4"><div className="flex justify-between"><h3 className="font-extrabold">Chapters</h3>{can('create')&&<button onClick={addChapter} className="border px-2 text-xs">+ Chapter</button>}</div>{chapters.map((chapter)=><button key={chapter.id} onClick={()=>setChapterId(chapter.id)} className="mt-2 block w-full border p-3 text-left text-sm"><strong>{chapter.chapterNumber}. {chapter.title}</strong><span className="float-right text-xs">{chapter.status}</span></button>)}</section>;else if(tab==='scenes')content=<section className="border bg-white p-4"><div className="flex justify-between"><h3 className="font-extrabold">Scenes</h3>{can('create')&&<button onClick={addScene} className="border px-2 text-xs">+ Scene</button>}</div>{scenes.map((scene,index)=><div key={scene.id} className="mt-2 flex items-center gap-2 border p-3 text-sm"><button onClick={()=>setSceneId(scene.id)} className="flex-1 text-left"><strong>{scene.sceneNumber}. {scene.title}</strong><span className="float-right text-xs">{scene.status}</span></button><button disabled={index===0} onClick={()=>{const next=[...scenes];[next[index-1],next[index]]=[next[index],next[index-1]];void run(async()=>{guard('edit');await reorderStoryScenes(chapterId,next.map((item)=>item.id));},()=>loadScenes(chapterId));}}><ChevronUp className="h-4 w-4"/></button></div>)}</section>;else if(tab==='locations')content=<section className="border bg-white p-4"><h3 className="font-extrabold">Locations</h3><p className="mt-2 text-sm text-[#667]">Scene locations reuse normalized Story Bible locations. Select a scene to assign its location from the inspector.</p></section>;

  return <div className="min-w-0 overflow-x-hidden"><div className="mb-3 flex gap-1 overflow-x-auto border-b border-[#cfd3d7] bg-white p-2">{tabs.map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={`shrink-0 px-3 py-2 text-xs font-bold ${tab===value?'bg-[#24282c] text-white':'hover:bg-[#eef0f1]'}`}>{label}</button>)}</div>{error&&<div role="alert" className="mb-3 flex items-center justify-between border border-red-300 bg-red-50 p-3 text-xs text-red-800"><span>{error}</span><button onClick={()=>void loadGlobal()} className="font-bold"><RefreshCw className="mr-1 inline h-3 w-3"/>Retry</button></div>}<button onClick={()=>setMobileTree((value)=>!value)} className="mb-2 inline-flex items-center gap-1 border bg-white px-3 py-2 text-xs font-bold lg:hidden"><ArrowLeft className="h-4 w-4"/>{mobileTree?'Back to workspace':'Series tree'}</button><div className="grid min-w-0 gap-3 lg:grid-cols-[230px_minmax(0,1fr)_300px]">{tree}<main className={`${mobileTree?'hidden':'block'} min-w-0 lg:block`}>{content}</main><div className={`${mobileTree?'hidden':'block'} lg:block`}>{inspectorPanel}</div></div><div className="sticky bottom-0 mt-3 flex items-center justify-between border bg-white p-2 text-[10px]"><span>{can('edit')?'Editing allowed':'Read only'} · {publicStoryBlocks(blocks).length} publishable blocks · {blocks.length-publicStoryBlocks(blocks).length} internal notes</span><span className="inline-flex items-center gap-1"><ShieldCheck className="h-3 w-3"/>Private production data excluded from publishing</span></div></div>;
};
