import React, { useState } from 'react';
import { Sigma, X, Check, Copy, Sparkles, BookOpen, Calculator, Layers } from 'lucide-react';
import { KatexMath } from '../common/KatexMath';
import { QuickLatexModal } from './QuickLatexModal';

interface MathFormulaModalProps {
  isOpen: boolean;
  onClose: () => void;
  onInsertFormula: (latex: string, label?: string) => void;
  initialLatex?: string;
  initialLabel?: string;
}

interface FormulaPreset {
  category: string;
  name: string;
  latex: string;
  label?: string;
  description: string;
}

const PRESET_FORMULAS: FormulaPreset[] = [
  // Algebra & Calculus
  {
    category: 'Algebra & Calculus',
    name: 'Quadratic Formula',
    latex: 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}',
    label: 'Eq. 1.1',
    description: 'Solutions to a second-degree polynomial polynomial equation.',
  },
  {
    category: 'Algebra & Calculus',
    name: 'Euler\'s Identity',
    latex: 'e^{i\\pi} + 1 = 0',
    label: 'Eq. 1.2',
    description: 'Profound link between exponential, imaginary, and trigonometric numbers.',
  },
  {
    category: 'Algebra & Calculus',
    name: 'Definite Integral',
    latex: '\\int_{a}^{b} f(x)\\,dx = F(b) - F(a)',
    label: 'Eq. 1.3',
    description: 'Fundamental Theorem of Calculus.',
  },
  {
    category: 'Algebra & Calculus',
    name: 'Taylor Series Expansion',
    latex: 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!} (x - a)^n',
    label: 'Eq. 1.4',
    description: 'Infinite sum of terms calculated from function derivatives.',
  },
  // Physics & Quantum
  {
    category: 'Physics & Quantum',
    name: 'Mass-Energy Equivalence',
    latex: 'E = m c^2',
    label: 'Eq. 2.1',
    description: 'Einstein\'s special relativity mass-energy equivalence equation.',
  },
  {
    category: 'Physics & Quantum',
    name: 'Schrödinger Wave Equation',
    latex: 'i\\hbar \\frac{\\partial}{\\partial t} \\Psi(\\mathbf{r},t) = \\hat{H}\\Psi(\\mathbf{r},t)',
    label: 'Eq. 2.2',
    description: 'Time-dependent wave equation describing quantum systems.',
  },
  {
    category: 'Physics & Quantum',
    name: 'Maxwell\'s Gauss Law',
    latex: '\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\varepsilon_0}',
    label: 'Eq. 2.3',
    description: 'Electric field divergence generated by charge distribution.',
  },
  // Probability & Statistics
  {
    category: 'Probability & Statistics',
    name: 'Gaussian Normal Distribution',
    latex: 'f(x) = \\frac{1}{\\sigma \\sqrt{2\\pi}} e^{-\\frac{1}{2}\\left(\\frac{x-\\mu}{\\sigma}\\right)^2}',
    label: 'Eq. 3.1',
    description: 'Probability density function for a normal distribution.',
  },
  {
    category: 'Probability & Statistics',
    name: 'Bayes Theorem',
    latex: 'P(A \\mid B) = \\frac{P(B \\mid A) P(A)}{P(B)}',
    label: 'Eq. 3.2',
    description: 'Conditional probability theorem for updating probabilities.',
  },
  // Linear Algebra
  {
    category: 'Linear Algebra',
    name: '2x2 Matrix Determinant',
    latex: '\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc',
    label: 'Eq. 4.1',
    description: 'Determinant calculation for a 2 by 2 square matrix.',
  },
  {
    category: 'Linear Algebra',
    name: 'Eigenvalue Equation',
    latex: '\\mathbf{A} \\mathbf{v} = \\lambda \\mathbf{v}',
    label: 'Eq. 4.2',
    description: 'Eigenvector and eigenvalue matrix operator relationship.',
  },
];

const SNIPPET_TOOLBAR = [
  { label: 'Fraction', latex: '\\frac{a}{b}' },
  { label: 'Power x²', latex: 'x^{2}' },
  { label: 'Subscript x₀', latex: 'x_{0}' },
  { label: 'Square Root', latex: '\\sqrt{x}' },
  { label: 'N-th Root', latex: '\\sqrt[n]{x}' },
  { label: 'Summation ∑', latex: '\\sum_{i=1}^{n} x_i' },
  { label: 'Integral ∫', latex: '\\int_{a}^{b} f(x)dx' },
  { label: 'Limit lim', latex: '\\lim_{x \\to 0} f(x)' },
  { label: 'Matrix (2x2)', latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}' },
  { label: 'Greek α β θ', latex: '\\alpha + \\beta = \\theta' },
  { label: 'Vector v⃗', latex: '\\vec{v}' },
  { label: 'Partial ∂', latex: '\\frac{\\partial y}{\\partial x}' },
];

export const MathFormulaModal: React.FC<MathFormulaModalProps> = ({
  isOpen,
  onClose,
  onInsertFormula,
  initialLatex = '',
  initialLabel = '',
}) => {
  const [latex, setLatex] = useState(initialLatex || 'f(x) = \\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}');
  const [mathLabel, setMathLabel] = useState(initialLabel || 'Eq. 1.1');
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [isQuickPaletteOpen, setIsQuickPaletteOpen] = useState(false);

  if (!isOpen) return null;

  const handleSnippetClick = (snippetLatex: string) => {
    setLatex((prev) => prev ? `${prev} ${snippetLatex}` : snippetLatex);
  };

  const handlePresetSelect = (preset: FormulaPreset) => {
    setLatex(preset.latex);
    if (preset.label) setMathLabel(preset.label);
  };

  const categories = ['All', 'Algebra & Calculus', 'Physics & Quantum', 'Probability & Statistics', 'Linear Algebra'];

  const filteredPresets = activeCategory === 'All'
    ? PRESET_FORMULAS
    : PRESET_FORMULAS.filter((p) => p.category === activeCategory);

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white border border-[#e0e0e0] rounded-xl max-w-3xl w-full p-6 space-y-6 max-h-[90vh] overflow-y-auto shadow-2xl">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[#f0f0f0] pb-4">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-md bg-[#ff6321]/10 text-[#ff6321]">
              <Sigma className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base text-[#2c2c2c]">LaTeX Math & Science Formula Builder</h3>
              <p className="text-xs text-[#666]">Author publication-quality scientific, mathematical, and statistical equations</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-md text-[#666] hover:text-[#2c2c2c] hover:bg-[#f0f0f0] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Live KaTeX Render Preview Box */}
        <div className="bg-[#f9f9f9] border border-[#e0e0e0] rounded-lg p-6 space-y-2 text-center relative">
          <div className="flex items-center justify-between text-[10px] font-mono font-bold text-[#666] uppercase border-b border-[#e0e0e0] pb-2 mb-2">
            <span className="flex items-center gap-1"><Sparkles className="w-3 h-3 text-[#ff6321]" /> Live KaTeX Math Preview</span>
            {mathLabel && <span className="text-[#ff6321] font-bold">{mathLabel}</span>}
          </div>

          <div className="py-4 min-h-[80px] flex items-center justify-center overflow-x-auto">
            <KatexMath math={latex} displayMode={true} className="text-xl" />
          </div>
        </div>

        {/* Input Controls */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4 text-xs">
          <div className="md:col-span-8 space-y-1">
            <label className="block text-[10px] uppercase font-bold text-[#666]">LaTeX Code Source</label>
            <textarea
              value={latex}
              onChange={(e) => setLatex(e.target.value)}
              placeholder="e.g. \int_{a}^{b} f(x)dx"
              rows={3}
              className="w-full bg-white border border-[#e0e0e0] rounded-md p-3 font-mono text-xs text-[#2c2c2c] focus:border-[#ff6321] focus:outline-none"
            />
          </div>

          <div className="md:col-span-4 space-y-1">
            <label className="block text-[10px] uppercase font-bold text-[#666]">Equation Number / Label</label>
            <input
              type="text"
              value={mathLabel}
              onChange={(e) => setMathLabel(e.target.value)}
              placeholder="e.g. Eq. (1.1)"
              className="w-full bg-white border border-[#e0e0e0] rounded-md px-3 py-2 font-mono font-bold text-xs text-[#2c2c2c] focus:border-[#ff6321] focus:outline-none"
            />
            <p className="text-[10px] text-[#666]">Appears on the right margin of published books</p>
          </div>
        </div>

        {/* Quick Snippet Insert Toolbar */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-[10px] uppercase font-bold text-[#666]">Quick LaTeX Operators & Symbols</label>
            <button
              type="button"
              onClick={() => setIsQuickPaletteOpen(true)}
              className="text-[#ff6321] hover:underline text-xs font-bold flex items-center gap-1 cursor-pointer"
            >
              <Layers className="w-3.5 h-3.5" /> Full Symbol Palette
            </button>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {SNIPPET_TOOLBAR.map((snip, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => handleSnippetClick(snip.latex)}
                className="px-2.5 py-1 rounded bg-[#f0f0f0] hover:bg-[#ff6321]/10 hover:text-[#ff6321] border border-[#e0e0e0] text-[11px] font-mono transition-colors"
                title={snip.latex}
              >
                {snip.label}
              </button>
            ))}
          </div>
        </div>

        {/* Presets & Formula Library */}
        <div className="space-y-3 pt-2 border-t border-[#f0f0f0]">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <label className="text-[10px] uppercase font-bold text-[#666] flex items-center gap-1">
              <Calculator className="w-3.5 h-3.5 text-[#ff6321]" /> Academic & Publishing Formula Presets
            </label>

            <div className="flex gap-1 overflow-x-auto pb-1">
              {categories.map((cat) => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setActiveCategory(cat)}
                  className={`px-2.5 py-1 rounded text-[11px] font-bold transition-all ${
                    activeCategory === cat
                      ? 'bg-[#ff6321] text-white shadow-xs'
                      : 'bg-[#f0f0f0] text-[#666] hover:text-[#2c2c2c]'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-48 overflow-y-auto pr-1">
            {filteredPresets.map((preset, idx) => (
              <div
                key={idx}
                onClick={() => handlePresetSelect(preset)}
                className="p-2.5 rounded-md bg-[#f9f9f9] border border-[#e0e0e0] hover:border-[#ff6321] hover:bg-white cursor-pointer transition-all space-y-1 group"
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-xs text-[#2c2c2c] group-hover:text-[#ff6321]">{preset.name}</span>
                  <span className="text-[10px] font-mono text-[#ff6321] font-bold">{preset.label}</span>
                </div>
                <p className="text-[11px] text-[#666] line-clamp-1">{preset.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Modal Actions */}
        <div className="flex items-center justify-end gap-3 pt-3 border-t border-[#f0f0f0]">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-md bg-[#f0f0f0] hover:bg-[#e0e0e0] text-[#2c2c2c] font-bold text-xs"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={() => {
              onInsertFormula(latex, mathLabel);
              onClose();
            }}
            className="px-5 py-2 rounded-md bg-[#ff6321] hover:opacity-90 text-white font-bold text-xs flex items-center gap-1.5 shadow-sm"
          >
            <Check className="w-4 h-4" /> Insert Equation Block
          </button>
        </div>

      </div>

      {/* Quick LaTeX Operators & Symbols Popup */}
      <QuickLatexModal
        isOpen={isQuickPaletteOpen}
        onClose={() => setIsQuickPaletteOpen(false)}
        onPasteLatex={(latexToAppend) => {
          setLatex((prev) => prev ? `${prev} ${latexToAppend}` : latexToAppend);
          setIsQuickPaletteOpen(false);
        }}
      />
    </div>
  );
};
